# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goris < Formula
  desc "A tool to get gopher image!"
  homepage "https://github.com/borischen0203/homebrew-goris"
  version "0.2.6"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/goris/releases/download/v0.2.6/goris_0.2.6_Darwin_x86_64.tar.gz"
      sha256 "2bbe8c3b77a02db3e145fc2cd8ada013742d2efb3aeea35f99ad89116e46ce98"
    end
    if Hardware::CPU.arm?
      url "https://github.com/borischen0203/goris/releases/download/v0.2.6/goris_0.2.6_Darwin_arm64.tar.gz"
      sha256 "0d91a57b562db4ace48c78b7bc488c92ee4a162d7486aae0c0a4a786e85967c7"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/goris/releases/download/v0.2.6/goris_0.2.6_Linux_x86_64.tar.gz"
      sha256 "c0886366a143644f7a99b5fb6e2619e436dc04c601e3e607b20fe3dee33c0ed4"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borischen0203/goris/releases/download/v0.2.6/goris_0.2.6_Linux_arm64.tar.gz"
      sha256 "a8c864c973369616eb746aebd94c79f69616b0cf06fb9763927db494c746c6c4"
    end
  end

  def install
    bin.install "goris"
  end
end
