# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goris < Formula
  desc "A tool to get gopher image!"
  homepage "https://goreleaser.com/borischen0203/goris"
  version "0.2.1"
  license "MIT"
  bottle :unneeded
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/goris/releases/download/v0.2.1/goris_0.2.1_macOS-64bit.tar.gz"
      sha256 "d63dc0d56c128682c1f1b382ef4ad2f4ed80fc1ed21884af24c047d8a98b3a49"
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  def install
    bin.install "goris"
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
