# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goris < Formula
  desc "A tool to get gopher image!"
  homepage "https://github.com/borischen0203/goris"
  version "0.0.9"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/goris/releases/download/v0.0.9/goris_0.0.9_macOS-64bit.tar.gz"
      sha256 "a3c6c93b5ba7c3f4cc07983726270dcf6cf96c4aa72f376a3641840becb1ffde"
    end
    if Hardware::CPU.arm?
      url "https://github.com/borischen0203/goris/releases/download/v0.0.9/goris_0.0.9_macOS-ARM64.tar.gz"
      sha256 "2a8ff5b05be1a35ca8fcf191739664316c8d9ccaf06f90786d5a9be7236b8741"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/goris/releases/download/v0.0.9/goris_0.0.9_Linux-64bit.tar.gz"
      sha256 "81fc13b11a353581662cf0919555b618c11a84f612827d571b63b6ffea9bac5f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borischen0203/goris/releases/download/v0.0.9/goris_0.0.9_Linux-ARM64.tar.gz"
      sha256 "aacd59ecfa0eeebd4b9f32acccff03a961b6a255886247b53901a58a58eb3597"
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  def install
    bin.install "goris"
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
